#set ctrl+Space as the leader prefix
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

#enable mouse usage
set -g mouse on

#increase history limit
set-option -g history-limit 5000

#start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

#rebind split commands
bind h split-window -hc "#{pane_current_path}"
bind v split-window -vc "#{pane_current_path}"

#rebind swapping windows
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

#preserve the current directory path
bind c new-window -c "#{pane_current_path}"

#toggling windows and sessions
bind Space last-window
bind-key C-Space switch-client -l

#vim like bindings for resizing
bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

#breaking and joining windows
bind j choose-window 'join-pane -h -s "%%"'
bind J choose-window 'join-pane -s "%%"'



